### ISSUE TITLE
no events are being fired 

### ISSUE THREAD

**Issue by moyvera** [metafizzy/isotope#1314] opened 2017-09-12 02:19 UTC
Hi, hope you can help me, I don't think this is an issue about the development, but I need your opinion please. 

I'm using npm to install isotope-layout and  laravel-mix ("webpack with shortcuts") to manage my frontend side

When I import isotope-layout 
```
import Isotope from 'isotope-layout';
```
i get this error
```
This dependency was not found:
masonry/masonry in ./~/isotope-layout/js/layout-modes/masonry.js
```
So I need to add in my webpack aliases this 
```javascript
  alias: {
            'masonry': 'masonry-layout'
          }
```
And looks like everything is working fine but not, when I try to fire events "layoutComplete" or "arrangeComplete" they are not being fired.

I used directly with the script tag this library and everything works fine, I see the events working. Just I don't know with this "configuration" I see the issue.

```javascript
var masonry       = $(this).find('.masonry__container');
// I work with this var ... and later
masonry.on('layoutComplete',function(){
  console.log('event fired !!!');
});

masonry.on( 'arrangeComplete', function( event, filteredItems ) {
  console.log('event fired !!!');
});

masonry.isotope({
  itemSelector: '.masonry__item',
  filter: defaultFilter,
  masonry: {
    columnWidth: '.masonry__item'
  }
});
```

**Comment by desandro** [comment] 2017-09-12 13:32
Thanks for submitting this issue. This is a bug that occurs when you load Isotope (or Masonry or Packery) via a module loader where `jQuery` is not available on the global object. jQuery events will not work.

The simplest work-around is to use Isotope's `on` method (as opposed to jQuery's `.on()`)

``` js
$grid.isotope( 'on', 'layoutComplete', function() {
  console.log('Isotope layout complete');
});

$grid.isotope( 'on', 'arrangeComplete', function( filteredItems ) {
  console.log('Isotope arrange complete');
});
```

I'll look into adding a fix for this for a future release.

**Comment by moyvera** [comment] 2017-09-12 16:57
Thanks for the quick answer 

Seems like it was a coincidence, I was all the morning trying to figure out but nothing. Isotope looks like it's working properly just the events don't, I see the transformations being applied in each item.

I just added the other line to my configuration according to this documentation 
```
https://isotope.metafizzy.co/extras.html#webpack
```

And this is "the new code"
```javascript
masonry.isotope({
  itemSelector: '.masonry__item',
  filter: defaultFilter,
  masonry: {
    columnWidth: '.masonry__item'
  }
});

masonry.isotope( 'on', 'layoutComplete', function() {
  console.log('Isotope layout complete');
});

masonry.isotope( 'on', 'arrangeComplete', function( filteredItems ) {
  console.log('Isotope arrange complete');
});
```

isotope version 3.0.4, no events fired

any idea ?

**Comment by ajax-zoom** [comment] 2017-09-12 22:30
Not sure when removeComplete supposed to be fired. However it is present in documention but is not present in sourcecode v3.0.4

**Comment by desandro** [comment] 2017-09-13 22:32
@ajax-zoom [`removeComplete`](https://isotope.metafizzy.co/events.html#removecomplete) is triggered after items have been removed with [Isotope's `remove` method](https://isotope.metafizzy.co/methods.html#remove). See demo https://codepen.io/desandro/pen/wErky

> it would be nice to have an event / hook which is fired when filter is applied but before positions are calculated and "arrange" is triggered.

You should be able to add this behavior with your own code, without the need of a custom event.

**Comment by moyvera** [comment] 2017-09-14 12:50
@desandro do you have any idea, suggestion about what's happening ? 

Kind regards!

**Comment by desandro** [comment] 2017-09-14 19:49
@moyvera Your code looks good. Another solution would be to get the Isotope instance and vanilla JS API

``` js
masonry.isotope({
 // ... options
});

var iso = masonry.data('isotope');

iso.on( 'layoutComplete', function() {
  console.log('Isotope layout complete');
});

iso.on( 'arrangeComplete', function( filteredItems ) {
  console.log('Isotope arrange complete');
});
```

**Comment by jrgd** [comment] 2017-10-03 16:39
@desandro I'm running in a similar issue (using trellis/bedrock/sage9) where it seems 'layoutComplete' is fired just fine, but 'arrangeComplete' is not. 

@moyvera : did you manage to work it out?

**Comment by moyvera** [comment] 2017-10-04 14:44
@jrgd no man, I did a work around but this is very specific for my project. 
I'm in stand-by continue developing I will return to this issue later.

**Comment by moyvera** [comment] 2017-10-24 17:22
I just did it...

For those working with laravel-mix and having a configuration based on jquery for this plugin...

I'm using script-loader, you can see more details here about it
```javascript
 https://github.com/webpack-contrib/script-loader
```
but essentially script-loader executes JS script once in global context 

Example...
```javascript
import 'script-loader!isotope-layout/dist/isotope.pkgd.js'
```
What I'm going to check later is using another module loader...

**Closed** 2017-10-24 17:22 UTC
Labels: bug

**Comment by Twisted101** [comment] 2018-02-03 03:06
hi ,it's work ;add   .isotope()    to the end.

	$grid.on('arrangeComplete', function() {
		console.log('arrangeComplete')
	}).isotope();`

**Comment by steveooo9** [comment] 2018-04-18 11:35
@desandro The issue is still relevant. See: https://github.com/metafizzy/isotope/issues/1397
