### ISSUE TITLE
Webpack problem

### ISSUE THREAD

**Issue by variable** [metafizzy/isotope#979] opened 2015-09-09 04:17 UTC
This is similar to the other issue https://github.com/desandro/masonry/issues/679, I tried your solution but still didn't work.

<pre><code>
ERROR in /Users/jameslin/projects/nzpg/~/isotope-layout/js/isotope.js
Module not found: Error: Cannot resolve module 'get-size/get-size' in /Users/jameslin/projects/nzpg/node_modules/isotope-layout/js
 @ /Users/jameslin/projects/nzpg/~/isotope-layout/js/isotope.js 17:4-31:8

ERROR in /Users/jameslin/projects/nzpg/~/isotope-layout/js/isotope.js
Module not found: Error: Cannot resolve module 'matches-selector/matches-selector' in /Users/jameslin/projects/nzpg/node_modules/isotope-layout/js
 @ /Users/jameslin/projects/nzpg/~/isotope-layout/js/isotope.js 17:4-31:8

ERROR in /Users/jameslin/projects/nzpg/~/isotope-layout/js/isotope.js
Module not found: Error: Cannot resolve module 'fizzy-ui-utils/utils' in /Users/jameslin/projects/nzpg/node_modules/isotope-layout/js
 @ /Users/jameslin/projects/nzpg/~/isotope-layout/js/isotope.js 17:4-31:8

ERROR in /Users/jameslin/projects/nzpg/~/isotope-layout/js/isotope.js
Module not found: Error: Cannot resolve module 'outlayer/outlayer' in /Users/jameslin/projects/nzpg/node_modules/isotope-layout/js
 @ /Users/jameslin/projects/nzpg/~/isotope-layout/js/isotope.js 17:4-31:8

ERROR in /Users/jameslin/projects/nzpg/~/alt/lib/index.js
Module not found: Error: Cannot resolve module 'flux' in /Users/jameslin/projects/nzpg/node_modules/alt/lib
 @ /Users/jameslin/projects/nzpg/~/alt/lib/index.js 23:12-27

ERROR in /Users/jameslin/projects/nzpg/~/isotope-layout/js/layout-mode.js
Module not found: Error: Cannot resolve module 'get-size/get-size' in /Users/jameslin/projects/nzpg/node_modules/isotope-layout/js
 @ /Users/jameslin/projects/nzpg/~/isotope-layout/js/layout-mode.js 11:4-15:15

ERROR in /Users/jameslin/projects/nzpg/~/isotope-layout/js/layout-mode.js
Module not found: Error: Cannot resolve module 'outlayer/outlayer' in /Users/jameslin/projects/nzpg/node_modules/isotope-layout/js
 @ /Users/jameslin/projects/nzpg/~/isotope-layout/js/layout-mode.js 11:4-15:15

ERROR in /Users/jameslin/projects/nzpg/~/isotope-layout/js/item.js
Module not found: Error: Cannot resolve module 'outlayer/outlayer' in /Users/jameslin/projects/nzpg/node_modules/isotope-layout/js
 @ /Users/jameslin/projects/nzpg/~/isotope-layout/js/item.js 10:4-13:15

ERROR in /Users/jameslin/projects/nzpg/~/isotope-layout/js/layout-modes/masonry.js
Module not found: Error: Cannot resolve module 'masonry/masonry' in /Users/jameslin/projects/nzpg/node_modules/isotope-layout/js/layout-modes
 @ /Users/jameslin/projects/nzpg/~/isotope-layout/js/layout-modes/masonry.js 12:4-16:15

ERROR in /Users/jameslin/projects/nzpg/~/alt/lib/store/StoreMixin.js
Module not found: Error: Cannot resolve module 'transmitter' in /Users/jameslin/projects/nzpg/node_modules/alt/lib/store
 @ /Users/jameslin/projects/nzpg/~/alt/lib/store/StoreMixin.js 11:19-41

ERROR in /Users/jameslin/projects/nzpg/~/alt/lib/store/AltStore.js
Module not found: Error: Cannot resolve module 'transmitter' in /Users/jameslin/projects/nzpg/node_modules/alt/lib/store
 @ /Users/jameslin/projects/nzpg/~/alt/lib/store/AltStore.js 19:19-41
</code></pre>

**Comment by desandro** [comment] 2015-09-15 00:44
The the [Webpack instructions](http://isotope.metafizzy.co/appendix.html#webpack) for Isotope

---

Install Isotope and imports-loader with npm.

``` bash
npm install isotope-layout
npm install imports-loader
```

In your config file, `webpack.config.js`, use the imports loader to disable define and set window for isotope-layout modules.

``` js
module.exports = {
  module: {
    loaders: [
      {
        test: /isotope-layout/,
        loader: 'imports?define=>false&this=>window'
      }
    ]
  }
};
```

You can then require('isotope-layout').

``` js
// main.js
var Isotope = require('isotope-layout');

var iso = new Isotope( '.grid', {
  // options...
});
```

Run webpack.

``` bash
webpack main.js bundle.js
```

**Comment by variable** [comment] 2015-09-15 01:12
That's pretty much what I have tried, this is my webpack config.
<pre><code>
var staticpath = __dirname + '/nzpg/static';
var webpack = require("webpack");

module.exports = {
  context: staticpath + '/js',
  entry: {
      lib: [
        './lib/common/jquery.js',
        './lib/common/isotope.js',
        './lib/common/functions.js',
        './lib/common/alt.js',
        './lib/comments/comment_box.js',
        './lib/comments/comment_box.jsx',
        './lib/likes/stores.js',
        './lib/likes/actions.js',
        './lib/likes/likes.js',
        './lib/likes/likes.jsx',
        './lib/votes/votes.js',
        './lib/votes/votes.jsx',
        './lib/competitions/stores.js',
        './lib/competitions/actions.js',
        './lib/competitions/entries.jsx',
        './lib/competitions/entries.js',
        './lib/common/controls.js',
      ],
      project: "./project.js",
      competitions: ["./competitions/competitions.js", "./competitions/competition_form.js"],
      photos: "./photos/photos.js",
  },
  output: {
    filename: "[name].js",
    path: staticpath + '/js_built',
  },
  plugins: [ new webpack.optimize.CommonsChunkPlugin('lib', 'lib.js') ],
  resolve: {
    root: staticpath + '/js',
    modulesDirectories: [__dirname+'/node_modules'],
    extensions: ['', '.js', '.jsx']
  },
  module: {
    loaders: [
      {
        test: /isotope-layout/,
        loader: 'imports?define=>false&this=>window'
        //test: /(isotope-layout|masonry|outlayer|item|get-size|fizzy-ui-utils\/utils)\.js$/,
        //loader: 'imports?define=>false'
      },
      {
        test: /\.js.*$/,
        exclude: /node_modules/,
        loaders: ["babel-loader"],
      },
    ],
  },
}var staticpath = __dirname + '/nzpg/static';
var webpack = require("webpack");

module.exports = {
  context: staticpath + '/js',
  entry: {
      lib: [
        './lib/common/jquery.js',
        './lib/common/isotope.js',
        './lib/common/functions.js',
        './lib/common/alt.js',
        './lib/comments/comment_box.js',
        './lib/comments/comment_box.jsx',
        './lib/likes/stores.js',
        './lib/likes/actions.js',
        './lib/likes/likes.js',
        './lib/likes/likes.jsx',
        './lib/votes/votes.js',
        './lib/votes/votes.jsx',
        './lib/competitions/stores.js',
        './lib/competitions/actions.js',
        './lib/competitions/entries.jsx',
        './lib/competitions/entries.js',
        './lib/common/controls.js',
      ],
      project: "./project.js",
      competitions: ["./competitions/competitions.js", "./competitions/competition_form.js"],
      photos: "./photos/photos.js",
  },
  output: {
    filename: "[name].js",
    path: staticpath + '/js_built',
  },
  plugins: [ new webpack.optimize.CommonsChunkPlugin('lib', 'lib.js') ],
  resolve: {
    root: staticpath + '/js',
    modulesDirectories: [__dirname+'/node_modules'],
    extensions: ['', '.js', '.jsx']
  },
  module: {
    loaders: [
      {
        test: /isotope-layout/,
        loader: 'imports?define=>false&this=>window'
        //test: /(isotope-layout|masonry|outlayer|item|get-size|fizzy-ui-utils\/utils)\.js$/,
        //loader: 'imports?define=>false'
      },
      {
        test: /\.js.*$/,
        exclude: /node_modules/,
        loaders: ["babel-loader"],
      },
    ],
  },
}
</code></pre>

**Comment by axelboc** [comment] 2015-10-13 23:45
Same issue here. The problem seems to be coming from the latest version of NPM. I don't get the issue with NPM v2.11.3 (the version that comes with Node v0.12.7), but I do with NPM v3.3.6.

**Comment by brikou** [comment] 2015-10-20 08:42
I confirm isotope is broken with npm3

```
npm install -g npm@3
npm install isotope-layout
# lol
```

**Comment by PJL101** [comment] 2015-11-20 18:22
I managed to get this working in npm3/node 5.1.0 by including the following workaround in my webpack.config.js:

```
resolve: {
    alias: {
      "masonry/masonry" : "masonry-layout",  
      "matches-selector/matches-selector": "desandro-matches-selector",
      "eventEmitter/EventEmitter": "wolfy87-eventemitter",
      "get-style-property/get-style-property": "desandro-get-style-property"
    }
  }
```

**Comment by desandro** [comment] 2015-11-24 14:12
With npm v3, try listing all isotope dependencies

``` js
module.exports = {
  module: {
    loaders: [
      {
        test: /isotope-layout|fizzy-ui-utils|desandro-|masonry|outlayer|get-size|doc-ready|eventie|eventemitter/,
        loader: 'imports?define=>false&this=>window'
      }
    ]
  }
};
```

**Comment by Spittal** [comment] 2015-12-02 01:32
I can confirm that @desandro method does work, however... This should be fixed in the core library to work with webpack

**Comment by lbineau** [comment] 2016-01-05 11:10
Hi,

Thank you for the quickfix. I got the same problem but for 'isotope-packery'.
```javascript
var IsotopePackery = require('isotope-packery');
```
```bash
ERROR in ./~/packery/js/packery.js
Module not found: Error: Cannot resolve module 'classie/classie' in /Users/lbineau/Sites/design-implemenation/node_modules/packery/js
 @ ./~/packery/js/packery.js 17:4-25:15

ERROR in ./~/packery/js/item.js
Module not found: Error: Cannot resolve module 'get-style-property/get-style-property' in /Users/lbineau/Sites/design-implemenation/node_modules/packery/js
 @ ./~/packery/js/item.js 11:4-16:15
```

I tried to modify the following but the error remains:
```javascript
loaders: [
  {
    test: /isotope\-|fizzy\-ui\-utils|desandro\-|masonry|outlayer|get\-size|doc\-ready|eventie|eventemitter|classie|get\-style\-property/,
    loader: 'imports?define=>false&this=>window'
  }
]
```

**Comment by desandro** [comment] 2016-01-05 12:57
@lbineau Try adding `packery` to the test RegEx

``` js
loaders: [
  {
    test: /isotope\-|fizzy\-ui\-utils|desandro\-|masonry|outlayer|get\-size|doc\-ready|eventie|eventemitter|classie|get\-style\-property|packery/,
    loader: 'imports?define=>false&this=>window'
  }
]
```

**Comment by lbineau** [comment] 2016-01-05 13:15
I've missed this one it's working now, thank you for the fast reply !

**Comment by dstarosta** [comment] 2016-03-17 04:19
The solution does not work for me using NPM 3.8.1. I have tried every loader suggestion. I use babel-loader, if that makes a difference.

The errors order changes when I added the loader. The errors are still the same. The first error changes from

ERROR in ../~/isotope-layout/js/isotope.js
Module not found: Error: Cannot resolve module 'get-size/get-size' in D:\Development\SomeApp\node_modules\isotope-layout\js
 @ ../~/isotope-layout/js/isotope.js 17:4-31:8

to

ERROR in ../~/isotope-layout/js/isotope.js
Module not found: Error: Cannot resolve module 'outlayer' in D:\Development\SomeApp\node_modules\isotope-layout\js
 @ ../~/isotope-layout/js/isotope.js 40:6-25

**Comment by dstarosta** [comment] 2016-03-31 04:12
I figured the problem out. If you are using babel loader, make sure to include the "transform-runtime" plugin to the "query" property of the loader.

`loaders: [{
            test: /\.js$/,
            exclude: /(node_module)/,
            loader: "babel",
            query: {
                plugins: ["transform-runtime", "transform-decorators-legacy"],
                presets: ["es2015", "stage-1"]
            }
}]`

**Comment by desandro** [comment] 2016-04-29 15:50
Isotope v3 has been released with [simplified Webpack integration](http://isotope.metafizzy.co/extras.html#webpack)

> In your config file, webpack.config.js, add these resolve aliases.

``` js
module.exports = {
  resolve: {
    alias: {
      'masonry': 'masonry-layout',
      'isotope': 'isotope-layout'
    }
  }
};
```

**Comment by nathanchase** [comment] 2016-05-17 16:26
@desandro How would one go about integrating **'isotope-packery'** alongside this new simplified Webpack integration?

I've got the following in my package.json:
"isotope-layout": "^3.0.0",
"isotope-packery": "^2.0.0",
"masonry-layout": "^4.1.0",

and then:
`var Isotope = require('isotope-layout');`
in my .js

how do I avoid this error:

`isotope.js:447 - Uncaught Error: No layout mode: packery`

?

**Comment by nathanchase** [comment] 2016-05-17 16:51
More feedback on the specific error:

`ERROR in ./~/isotope-packery/packery-mode.js
Module not found: Error: Cannot resolve module 'isotope-packery/js/layout-mode'`

**Comment by desandro** [comment] 2016-05-17 17:17
@nathanchase Looks like you need to require `isotope-packery`. I was able to make it work with the [simplified config above](https://github.com/metafizzy/isotope/issues/979#issuecomment-215771272). My `.js`:

``` js
var Isotope = require('isotope-layout');
require('isotope-packery');

new Isotope('.grid', {
  layoutMode: 'packery'
});
```

**Comment by nathanchase** [comment] 2016-05-17 17:28
I've got 
`var Isotope = require('isotope-layout');
require('isotope-packery');`

and still get `isotope.js:447 Uncaught Error: No layout mode: packery`

If I add a `console.log(packery);`, I get `Unhandled rejection ReferenceError: packery is not defined`

**Comment by nathanchase** [comment] 2016-05-17 18:28
Maybe this will help. Here's my relevant part of my webpack.config.js:

```
alias: {
            listservice: 'listservice',
            matchupservice: 'matchupservice',
            movieservice: 'movieservice',
            rankservice: 'rankservice',
            userservice: 'userservice',
            appdata: 'appdata',
            'imagesLoaded': 'imagesloaded',
            'flickity': 'flickity',
            'isotope': 'isotope-layout',
            'masonry': 'masonry-layout',
            'isotope-packery': 'isotope-packery',
            'eventEmitter/EventEmitter': 'wolfy87-eventemitter/EventEmitter',
            'get-style-property': 'desandro-get-style-property',
            'matches-selector': 'desandro-matches-selector',
            'classie': 'desandro-classie'
        }
```

Flickity works fine. Isotope works fine when in masonry or default mode. It's only when I try to use `packery` mode that it falis with `isotope.js:447 Uncaught Error: No layout mode: packery`

**Comment by desandro** [comment] 2016-05-17 18:33
Hmm, try removing `'isotope-packery': 'isotope-packery'`. Shouldn't be necessary.

**Comment by nathanchase** [comment] 2016-05-17 18:35
Yeah, tried removing it. Same result. ` No layout mode: packery `

**Comment by nathanchase** [comment] 2016-05-17 18:55
Here's something:

In `isotope-layout''s package.json, it has a"

`"main: "js/isotope.js",`

which resolves, because there is a path under isotope-layout to js/isotope.js

BUT

in isotope-packery's package,json, it has:

`"main": "js/packery.js",` which does NOT resolve, because there's no 'js' folder.

There's just:

node_modules
sandbox
and root files

Could that be the issue?

**Comment by nathanchase** [comment] 2016-05-17 19:02
Here's webpack's build output... it seems to be getting everything for packery, but somehow still isn't available:

[397] ./~/isotope-layout/js/isotope.js 17.3 kB {1} [built]
  [398] ./~/isotope-layout/~/get-size/get-size.js 5.3 kB {1} [built]
  [399] ./~/isotope-layout/~/desandro-matches-selector/matches-selector.js 1.3 kB {1} [built]
  [400] ./~/isotope-layout/~/fizzy-ui-utils/utils.js 5.79 kB {1} [built]
  [401] ./~/isotope-layout/~/outlayer/outlayer.js 22 kB {1} [built]
  [402] ./~/isotope-layout/~/outlayer/~/ev-emitter/ev-emitter.js 2.55 kB {1} [built]
  [403] ./~/isotope-layout/~/outlayer/item.js 14.7 kB {1} [built]
  [404] ./~/isotope-layout/js/layout-mode.js 4.02 kB {1} [built]
  [405] ./~/isotope-layout/js/layout-modes/masonry.js 1.83 kB {1} [built]
  [406] ./~/isotope-layout/~/masonry-layout/masonry.js 6.45 kB {1} [built]
  [407] ./~/isotope-layout/js/layout-modes/fit-rows.js 1.4 kB {1} [built]
  [408] ./~/isotope-layout/js/layout-modes/vertical.js 1.1 kB {1} [built]
  [409] ./~/isotope-layout/js/item.js 1.77 kB {1} [built]
  [410] ./~/isotope-packery/packery-mode.js 2.37 kB {1} [built]
  [411] ./~/isotope-packery/~/isotope-layout/js/layout-mode.js 4.02 kB {1} [built]
  [412] ./~/isotope-packery/~/isotope-layout/~/get-size/get-size.js 5.3 kB {1} [built]
  [413] ./~/isotope-packery/~/isotope-layout/~/outlayer/outlayer.js 22 kB {1} [built]
  [414] ./~/isotope-packery/~/isotope-layout/~/outlayer/~/ev-emitter/ev-emitter.js 2.55 kB {1} [built]
  [415] ./~/isotope-packery/~/isotope-layout/~/fizzy-ui-utils/utils.js 5.79 kB {1} [built]
  [416] ./~/isotope-packery/~/isotope-layout/~/desandro-matches-selector/matches-selector.js 1.3 kB {1} [built]
  [417] ./~/isotope-packery/~/isotope-layout/~/outlayer/item.js 14.7 kB {1} [built]
  [418] ./~/isotope-packery/~/packery/js/packery.js 17.7 kB {1} [built]
  [419] ./~/isotope-packery/~/packery/~/get-size/get-size.js 5.3 kB {1} [built]
  [420] ./~/isotope-packery/~/packery/~/outlayer/outlayer.js 22 kB {1} [built]
  [421] ./~/isotope-packery/~/packery/~/outlayer/~/ev-emitter/ev-emitter.js 2.55 kB {1} [built]
  [422] ./~/isotope-packery/~/packery/~/outlayer/~/fizzy-ui-utils/utils.js 5.79 kB {1} [built]
  [423] ./~/isotope-packery/~/packery/~/outlayer/~/fizzy-ui-utils/~/desandro-matches-selector/matches-selector.js 1.3 kB {1} [built]
  [424] ./~/isotope-packery/~/packery/~/outlayer/item.js 14.7 kB {1} [built]
  [425] ./~/isotope-packery/~/packery/js/rect.js 3.28 kB {1} [built]
  [426] ./~/isotope-packery/~/packery/js/packer.js 4.74 kB {1} [built]
  [427] ./~/isotope-packery/~/packery/js/item.js 3.33 kB {1} [built]

**Comment by nathanchase** [comment] 2016-05-17 20:43
So, I blew out my node_modules folder, let it regrab everything, and now it's fine. Argh! Frustrating!

For reference, my webpack.config.js:

```
alias: {
            'imagesLoaded': 'imagesloaded',
            'flickity': 'flickity',
            'masonry': 'masonry-layout',
            'isotope': 'isotope-layout',
            'eventEmitter/EventEmitter': 'wolfy87-eventemitter/EventEmitter',
            'get-style-property': 'desandro-get-style-property',
            'matches-selector': 'desandro-matches-selector',
            'classie': 'desandro-classie'
        }
```

**Comment by desandro** [comment] 2016-11-06 15:13
I'm closing this issue as Webpack use with Isotope has been simplified in v3, see comment above https://github.com/metafizzy/isotope/issues/979#issuecomment-219788833

If you run into issues with Isotope and Webpack, please open a new issue.

**Closed by desandro** 2016-11-06 15:13 UTC
Labels: module loader
