### ISSUE TITLE
Transitions issue on IOS Devices - Some items disappear during transition

### ISSUE THREAD

**Issue by lolo34140** [metafizzy/isotope#985] opened 2015-10-01 01:19 UTC
Hello,

I noticed that on IOS devices (tested on an iPad and an iPhone on ios9) there are a kind of flicker during animation when sorting or filtering isotope. Some items in the grid disappear during transition and reappear only after arrange completed.

It's really annoying because animations seem completely break without transitions and missing elements... but items are correctly arranged.

http://fiddle.jshell.net/3a1p59h9/36/

Lolo

**Comment by senner007** [comment] 2015-10-03 16:30
I can confirm that.

**Comment by lolo34140** [comment] 2015-10-15 09:37
Hello,

Any news about this issue? I really need to fix ASAP for a project. It seems to be a transform issue on IOS. If I add a `translateZ(0)`, it partially fixes the issue. But all child elements inside items still flicker whatever the transform fix property I try to add...

Lolo

**Comment by desandro** [comment] 2015-10-15 14:29
Testing on an iOS8 iPhone and I can't reproduce the flicker. Sorry, I do not have a solution. Maybe try [`will-change`](https://developer.mozilla.org/en-US/docs/Web/CSS/will-change)

**Comment by lolo34140** [comment] 2015-10-15 15:50
Here you will find a video on an iPhone 6: http://www.filedropper.com/isotopeiosissue
The same issue appears on iPad also.

There is also this on android phone (tested on a Samsung Galaxy). With Android devices, items don't move at all during transition then directly appear in another position.

And on Window 10 on IE11 there is the same issue. I need to retest on it to be sure but I already observed.

css will-change property seems to not solve the issue. And also this property is a little bit tricky so I will not use it (but it doesn't solve the issue).

This issue is really annoying, sometimes on IOS devices, all item disappear during transition and then reappear.

Loïc

**Comment by lolo34140** [comment] 2015-10-22 08:20
Any news about this issue?

Loïc

**Comment by desandro** [comment] 2016-11-06 15:16
I'm closing this issue as its been quiet for over a year. I'm hoping its been resolved in updates to Blink & WebKit browsers.

**Closed by desandro** 2016-11-06 15:16 UTC
Labels: bug
