### ISSUE TITLE
Strange positioning of items with percent width when resizing or filtering in Safari

### ISSUE THREAD

**Issue by w4nderlust** [metafizzy/isotope#949] opened 2015-07-08 20:30 UTC
I'm trying to make a fitRows grid with Isotope v2. The single grid items have a percent width of 50% so that it adapts well to the screen size making it responsive. The layout works good, but when i filter it or i resize the window width manually, the single grid elements (the external right ones) move strangely, first they go right and then get back in position again. In particular the external right ones shift to the right and then came back.
The problem seems to be present on Safari, but not on Chrome and Firefox (haven't tried on IE).
You may experience the problem in this [JSFiddle](https://jsfiddle.net/2dkot43a/1/).
I first was thinking that i was doing something wrong (I was trying only on Safari) so i asked on StackOverflow, but then i realized that it was working ok on Firefox and Chrome, so maybe it's a Safari related issue in Isotope itself, that's why I'm writing it here.

**Comment by lspoor** [comment] 2015-08-10 15:07
Not sure if this is the same issue or its just another issue like mine ( https://github.com/metafizzy/isotope/issues/968 ) my issue is only happening on iPhone but I just opened this fiddle on my iPhone and I'm getting the same problem

**Comment by desandro** [comment] 2015-08-20 19:45
Thanks for reporting this issue. Closing as a duplicate of #948.

**Closed by desandro** 2015-08-20 19:45 UTC
