### ISSUE TITLE
Error in bower install

### ISSUE THREAD

**Issue by JohnBueno** [metafizzy/isotope#911] opened 2015-05-07 20:08 UTC
I just installed isotope via bower:

bower install isotope --save

Before I even try to implement I start getting the following error.

Uncaught TypeError: Cannot read property 'Item' of undefined
(outlayer.js line 42)

Tried trouble shooting it for a bit to no avail.

**Comment by desandro** [comment] 2015-05-07 22:03
Sounds like you're missing some files in your build process. What are you using?

**Comment by Braus** [comment] 2015-05-13 07:18
Any updates?
I am having the same issue.

Cheers

**Comment by spdaly** [comment] 2015-05-15 14:51
+1

**Comment by spdaly** [comment] 2015-05-15 15:17
I found the following issue on a dependent JS (https://github.com/metafizzy/outlayer/issues/33).  The problem is with the Bower setup and using wiredep.

I mod'd the bower.json file to use the pkgd JS version of Isotope. Not a permanent fix, but gets me through this issue.

**Comment by ethanclevenger91** [comment] 2015-05-22 21:25
Try adding the following to your own bower overrides:

```
"isotope": {
      "main": "dist/isotope.pkgd.min.js",
      "dependencies": null
    }
```

**Comment by xelhark** [comment] 2015-05-26 09:07
It might be related to https://github.com/metafizzy/isotope/issues/879 . I solved it using @EHLOVader 's solution

**Comment by desandro** [comment] 2015-06-04 15:56
Closing this issue here as a duplicate of #879.

**Closed by desandro** 2015-06-04 15:56 UTC

**Comment by NeXTs** [comment] 2015-10-02 21:32
@ethanclevenger91 Thank you! This solved my problem with "bower-main-files" and dependent outlayer plugin

**Comment by nixoschu** [comment] 2015-11-02 10:01
I needed to set dependencies to an empty array/object instead of null as @ethanclevenger91 pointed out

```
  "overrides": {
    "isotope": {
      "main": "dist/isotope.pkgd.min.js",
      "dependencies": {}
    }
  }
```

**Comment by eeiswerth** [comment] 2015-11-05 19:20
+1 @nixoschu
