### ISSUE TITLE
Wiredep issue - "Cannot read property 'Item' of undefined" 

### ISSUE THREAD

**Issue by laxmisalunkhe** [metafizzy/isotope#1008] opened 2015-11-30 05:30 UTC
Getting error while installed isotope v2.2.2.

**Comment by desandro** [comment] 2015-11-30 14:45
Are you using wiredep? Add this to your config

``` js
"overrides": {
    "isotope": {
      "main": [
        "js/item.js",
        "js/layout-mode.js",
        "js/isotope.js",
        "js/layout-modes/vertical.js",
        "js/layout-modes/fit-rows.js",
        "js/layout-modes/masonry.js"
      ],
    },
    "outlayer": {
      "main": [
        "item.js",
        "outlayer.js"
      ]
    }
  }
```

**Comment by laxmisalunkhe** [comment] 2015-12-01 04:57
I have installed Isotope via Bower. Yes I am using wiredep but not sure about where to add this configuration? @desandro Can you provide more detail about config.

**Comment by laxmisalunkhe** [comment] 2015-12-01 05:34
@desandro I have added the configuration provided by you in Bower configuration file but still it's shows same error.

**Comment by desandro** [comment] 2015-12-02 13:54
Sorry about that, I had a trailing comma. I've edited the config code above. Try it again.

**Comment by desandro** [comment] 2015-12-02 19:05
Closing as a duplicate of #879

**Closed by desandro** 2015-12-02 19:05 UTC

**Comment by laxmisalunkhe** [comment] 2015-12-03 04:55
@desandro I checked #879 but still my issue is not resolved after adding above code.
