### ISSUE TITLE
Isotope Re Layout not working in Elementor

### ISSUE THREAD

**Issue by steve231293** [metafizzy/isotope#1504] opened 2019-07-05 01:39 UTC
Hello @desandro,
First of all, thank you so much for making awesome jquery plugins.

I have a problem with isotope layout in Elementor. I found the fixes for a week but without any solutions.

In Frontend & Editor Mode layout is working properly. But in Elementor Editor, Whenever i change any settings ( re-call init isotope function ) then layout render not properly.

I'm trying re-call layout but without luck.
`grid.isotope( 'layout' );`

I'm also trying call directly in Chrome Console log but have the same problem.

These are some screenshots about these problems:

Editor mode: Before change any settings: 
[http://prntscr.com/oascdk](http://prntscr.com/oascdk)

Editor mode: After change a setting: ( For eg: Columns 4 -> 3  )
then layout broken: 
[http://prntscr.com/oasdd4](http://prntscr.com/oasdd4)
[http://prntscr.com/oasdqw](http://prntscr.com/oasdqw)

This issue with same my problem:
[https://github.com/elementor/elementor/issues/6756](https://github.com/elementor/elementor/issues/6756)

**Comment by desandro** [comment] 2019-07-06 18:34
Sorry, I will not be able to debug this problem with Elementor. Closing as a duplicate of #1456

**Closed by desandro** 2019-07-06 18:34 UTC
