### ISSUE TITLE
[Bug] Transition issue in Chrome on rearrange

### ISSUE THREAD

**Issue by RafaelKr** [metafizzy/isotope#1036] opened 2016-02-12 08:59 UTC
Hi everyone,

I had an issue with isotope, when the items rearranged (clicking on filter, resizing window, ...).
The items were jittering/bouncing/jumping (my english isn't that good, that I know a really good word for it), a bit like in this video:
https://drive.google.com/file/d/0B5OxMCWiLhrMcmZUYm56YkFzdGs/view?usp=sharing
(Source: http://stackoverflow.com/questions/27748559/isotope-items-are-jumping; This person had a similar problem)

This issue happened in Chrome (Probably all browsers that use the WebKit-/Blink-Renderer), but not in Firefox.

I solved this problem by using the css-style "transition-duration: 0s;" on the tiles (itemSelector: '.element-item'). Now it works like a charme.

Great project by the way!

P.S. I don't have much time atm, when I have time I can post a live-demo and maybe I can also create a pull request, that fixes that.

Edit: Additionally the tiles sometimes also didn't position correctly, sometimes they overlapped or had too big gaps between, this also disappears with my mentioned solution.

**Comment by desandro** [comment] 2016-02-12 15:36
This double transition bug is likely caused by `transition: all` CSS. If you are using CSS transitions, set your transition properties to _only_ be the properties you are transitioning.

Duplicate of #660, #1031, #749 

I'll have to add something about this to the docs.

**Closed** 2016-02-12 16:02 UTC
