### ISSUE TITLE
Isotope filter function returning 0 for Element Item

### ISSUE THREAD

**Issue by matthewattanasio** [metafizzy/isotope#1542] opened 2020-04-29 02:31 UTC
I am using the vanilla JS version of Isotope to create a filter function like so

```
isotope.arrange({
    filter: function(element) {
        console.log(element)
```

However, the value returned for the variable element is `0` and not an `HTMLElement` like it is on my local machine.

When logging the `isotope.getItemElements()` beforehand it returns all the items so I know it has been instantiated correctly.

Any Help would be much appreciated

**Test case:** https://codepen.io/matthewattanasio/pen/qBOjeMr

**Comment by matthewattanasio** [comment] 2020-04-30 07:38
So I think the documentation is not correct https://isotope.metafizzy.co/filtering.html#functions states the following

```
iso.arrange({
  // item element provided as argument
  filter: function( itemElem ) {
    var number = itemElem.querySelector('.number').innerText;
    return parseInt( number, 10 ) > 50;
  }
});
```

However in my test case https://codepen.io/matthewattanasio/pen/qBOjeMr the filter function has two arguments and its the second argument that returns the element e.g. the above code should actually be  

```
iso.arrange({
  // item element provided as argument
  filter: function( itemElem1, itemElem2 ) {
    var number = itemElem2.querySelector('.number').innerText;
    return parseInt( number, 10 ) > 50;
  }
});
```

**Comment by PaulMorel** [comment] 2020-06-22 17:28
Happy to have found this issue. This is also the case for me. The second argument of the filter function returns the element instead of the first.

Might this be a regression on version 3.0.6?

**Comment by powerbuoy** [comment] 2021-01-23 12:28
Having the same issue. What's absolutely baffling is that for me it works locally in MacOS Chrome. But live it doesn't work on MacOS Chrome, it does however work in Android Chrome as well as Safari.

Screenshot of code:

<img width="292" alt="Screenshot 2021-01-23 at 13 25 50" src="https://user-images.githubusercontent.com/1027780/105578208-bd697680-5d7e-11eb-9aa9-14539d51ffb4.png">

Screenshot of Chrome console from local site:

<img width="209" alt="Screenshot 2021-01-23 at 13 25 46" src="https://user-images.githubusercontent.com/1027780/105578216-c5c1b180-5d7e-11eb-8cf0-89f5996f7197.png">

Screenshot of Chrome console from live site:

<img width="134" alt="Screenshot 2021-01-23 at 13 25 56" src="https://user-images.githubusercontent.com/1027780/105578228-d2dea080-5d7e-11eb-985a-5dd0bd4a196c.png">

Screenshot of Safari console from live site:

<img width="312" alt="Screenshot 2021-01-23 at 13 27 09" src="https://user-images.githubusercontent.com/1027780/105578235-dbcf7200-5d7e-11eb-86d7-4259041d7771.png">

How is that even possible? :P

**Comment by powerbuoy** [comment] 2021-01-23 12:48
Ok so using the second argument instead works, but not locally haha. On localhost the second argument is undefined. I solved it by doing this:

```
filter: (elementLocallyAndInSafariAndAndroidEtc, elementInSomeOtherCases) => {
	const element = elementLocallyAndInSafariAndAndroidEtc || elementInSomeOtherCases;
```

😂

**Comment by thesublimeobject** [comment] 2021-01-23 19:58
@powerbuoy (along with anyone else in this thread) —

I haven't actually tested any of these examples yet, but I'm pretty certain I know exactly what this issue is. I ran into it a few times awhile back, but I wrote a function around this so that I didn't have to worry about it anymore (don't remember exactly what I did).

I think there may be one other thread that mentions this issue as well.

I've been working on some different implementations of some of this internal functionality, so I will try to get an official fix merged whenever I get a chance. Have some patience with me though, it might be a bit before I get to it, but since there's definitely a temporary workaround, I assume, for the time being, it's not a total blocker for everyone?

**Comment by powerbuoy** [comment] 2021-01-23 20:57
Would be really interesting to know what's causing it? I've never experienced a JS bug that works fine on my machine but not on prod... In the same browser. Very odd indeed. But yea using argument 2 on prod solved it so no rush.

**Comment by thesublimeobject** [comment] 2021-01-23 23:46
@powerbuoy — Obviously I'm not trying to discount your experience, but typically when I run into local vs production issues like that, there tends to be a reason for it that I just missed the first time I looked because I was searching for something else. For example, are you 100% sure that the version of Isotope (and perhaps even its dependencies) are exactly the same on production and local? Are you using a CDN that could be pulling in a slightly different version because of an unspecified version, or something like that?

Perhaps that's not it, but I just figured I would throw out some ideas.

**Comment by powerbuoy** [comment] 2021-01-24 00:15
My first thought was "obviously it's because I'm running a non minified / development version of the JS on my local machine" so I ran it through the prod build (we use webpack and have no minification or sourcemaps during `npm run dev` but here I tried `npm run build` which is used during deployment) but it _still_ worked fine on my machine.

Granted I haven't checked that the `app.js` file is identical (it should be! otherwise something is very wrong) so it could be that...

We do use GitHub actions to deploy, so the code gets installed and built on GitHub, so there might be some differencies there, so I will absolutely do a diff on the two `app.js` files once I'm back to my work laptop.

But it's still very surprising that it works fine in Safari and Chrome Android but not Chrome MacOS? And why would the first argument be a `0` and the second the actual element whereas locally (and again, in Safari and Android Chrome) the first argument is the element and the second is undefined?

There's no CDN in place. The site is still being developed and isn't launched yet.

**Comment by thesublimeobject** [comment] 2021-01-24 01:36
Hmm I'm not sure off the top of my head. Let me know what come of your diff, but I'll be sure to track down the function from the source whenever I have a minute (probably tomorrow).

Usually when there's a browser disagreement related to argument order I tend to think something tied to events, as I believe one of the three browsers used to pass the event object in a different order than the others when passing the handler a function as opposed to calling it anonymously; although, given that you're saying the argument is 0, I highly doubt that's the case. Plus, I'm pretty sure that has since been fixed, as I haven't encountered it in awhile.

Either way, let me know what you find. It could certainly be some combination of minor version differences along with some sort of webpack dependency decision (which may also depend heavily on your setup—and if we need to dig into that, we can). But once I get a chance to take a look at the the source function again tomorrow, I should be a lot more helpful. I'd prefer not to continue just guessing, even if I believe my guesses are informed :D.

**Comment by powerbuoy** [comment] 2021-01-24 15:10
Ok I realise I'm going to come off as a massive noob here, but the problem has suddenly disappeared from the live site 😂

I added back my console.logs like this, and did a diff between the built app.js live and locally and couldn't find any differences:

```
filter: (elementLocallyAndInSafariAndAndroidEtc, elementInSomeOtherCases) => {
	const element = elementLocallyAndInSafariAndAndroidEtc || elementInSomeOtherCases;

	if (elementLocallyAndInSafariAndAndroidEtc) {
		console.log('The first argument is the element:');
		console.dir(elementLocallyAndInSafariAndAndroidEtc);
	}
	else {
		console.log('The second argument is the element:');
		console.dir(elementInSomeOtherCases);
	}
```

And where on the live site yesterday it said "The second argument is the element" today it says "The first argument is the element" (which is what it's always said locally).

I have worked on the site, but not that particular file, so I'm baffled.

Clearly this problem is real though as others have experienced it (the first argument being `0`), but why I only experienced it live and never locally is still a mystery.

**Comment by thesublimeobject** [comment] 2021-01-25 20:10
@powerbuoy Well, that's good to hear, I guess haha. I'm glad it's working for you now. I'm definitely still going to look into it since, as you said, others have definitely had issues. 

Be sure to let me know if you come across it again before I have a chance to dig in.

**Comment by desandro** [comment] 2021-06-13 17:30
Thanks for digging into this. Let's open a fresh issue if run into a similar issue.

**Closed as completed by desandro** 2021-06-13 17:30 UTC

**Comment by theenoahmason** [comment] 2021-09-17 02:51
Just ran into this now in 2021 with fresh install of isotope.

Strangely enough this issue is only happening for me in the WordPress Customizer panel. Solved with `const item = item1 || item2`.

**Comment by maximebeguin** [comment] 2022-08-11 19:48
Same double argument issue here (different order on local vs live site). fixed it with const item = item1 || item2. thank you!
