### ISSUE TITLE
percentPosition only stops transitions if transitionDuration defined

### ISSUE THREAD

**Issue by hirasso** [metafizzy/isotope#912] opened 2015-05-08 15:43 UTC
Hi there, just noticed something. I want to use `percentPosition` to disable transitions on resize. At first it worked great (no transitions on resize), but when I removed the option `transitionDuration` from the script, the transitions came back. This is my code:
```javascript
$(".grid").isotope({
      itemSelector: '.grid_item',
      masonry: {
        columnWidth: '.grid_sizer'
      },
      percentPosition: true
      transitionDuration: 0 // If I remove this, transitions come back
});
```

**Comment by desandro** [comment] 2015-05-08 15:58
Can you provide a **reduced test case**? Try forking this demo http://codepen.io/desandro/pen/xGZOEV

Is this occurring in Safari? If so, this issue may be a duplicate of desandro/masonry#698

**Comment by hirasso** [comment] 2015-05-08 16:11
Wow, you are <i>on-line</i>! :)
Here's my test case: http://codepen.io/hirasso/pen/qdbNRq

I think it might have something to do with the media queries? Maybe it even is a feature and not a bug ;)

**Comment by hirasso** [comment] 2015-05-08 16:40
I can reproduce the animating betweeen different breakpoints in chrome, safari and firefox.

**Comment by desandro** [comment] 2015-05-08 17:24
Thanks for that!

Looks like everything is working as intended. `percentPosition` sets item position in percent values, rather than pixel values. On window resize, the items position will scale proportionally and you shouldn't see a position. `transitionDuration: 0` disables all transitions. Item positions will be set immediately with no transitions.

In your demo, you'll notice there's only a transition in position when the items' size changes due to the media query. If you want to remove this transition, you can set `transitionDuration: 0`.

**Closed by desandro** 2015-05-08 17:24 UTC
Labels: test case required
