### ISSUE TITLE
Can I disable isotope at low resolutions somehow? (Strange item resizing issue)

### ISSUE THREAD

**Issue by Nomenator** [metafizzy/isotope#858] opened 2015-01-29 19:38 UTC
Using bootstrap and isotope I came across strange issue in small resolutions:
When window becomes narrower than 768px, items stop following column width instructions and start clipping through each other.
Here’s a snippet with isotope:
http://www.bootply.com/render/yfVsdRamtm (code http://www.bootply.com/yfVsdRamtm)
![image](https://cloud.githubusercontent.com/assets/10762749/5964728/61242332-a7c4-11e4-9162-13e7b152776f.png)

There’s a snippet without isotope:
http://www.bootply.com/render/RdTI0qyO4J (code http://www.bootply.com/render/yfVsdRamtm)
![image](https://cloud.githubusercontent.com/assets/10762749/5964734/6c13bbf4-a7c4-11e4-9b82-95fa9d648367.png)

It looks damn good with isotope up until the point when this breaks.
Can I somehow disable isotope at low res?

**Comment by lietzi** [comment] 2015-02-20 12:07
I solved this kind of problem like this:
```
    // thx to louisremi for on_resize standalone
    on_resize = function (c,t) {
      onresize = function() {
        clearTimeout(t);
        t=setTimeout(c,100);
      };
        return c;
    };

    var isotopeFlag = false;

    on_resize(function() {
      if (($(window).width() < 500) && isotopeFlag) {
        // destroy isotope at small windows-sizes
        $('#content').isotope('destroy');
        isotopeFlag = false;
      } else if (($(window).width() >= 500) && !isotopeFlag){
        // rebuild isotope on big screens
        $('#content').isotope({
          layoutMode: 'masonry',
          itemSelector: '.iso-block',
          masonry: { 'columnWidth': 240 }
        });
        isotopeFlag = true;
      }
    })();
```

**Comment by desandro** [comment] 2015-08-20 19:46
Sorry, Isotope does not support this feature. But there is an open feature request. Closing as a duplicate of #917.

**Closed by desandro** 2015-08-20 19:46 UTC
